sonar.organization=panenka29
sonar.projectKey=Panenka29_sopra-fs26-group-05-client

sonar.projectName=sopra-fs26-group-05-client
sonar.sources=app

sonar.exclusions=**/node_modules/**,**/.next/**,**/out/**,**/coverage/**
